#!/bin/sh

LED_SYSFS="blue:mesh"
LED_UCI="system.led_podkop"

led_on() {
    uci set ${LED_UCI}=led
    uci set ${LED_UCI}.name='podkop'
    uci set ${LED_UCI}.sysfs="${LED_SYSFS}"
    uci set ${LED_UCI}.trigger='default-on'
    uci commit system
    /etc/init.d/led restart
}

led_off() {
    uci set ${LED_UCI}=led
    uci set ${LED_UCI}.name='podkop'
    uci set ${LED_UCI}.sysfs="${LED_SYSFS}"
    uci set ${LED_UCI}.trigger='none'
    uci commit system
    /etc/init.d/led restart
}

led_blink() {
    echo "timer" > "/sys/class/leds/${LED_SYSFS}/trigger"
    echo 10 > "/sys/class/leds/${LED_SYSFS}/delay_on"
    echo 10 > "/sys/class/leds/${LED_SYSFS}/delay_off"
}

toggle() {
    led_blink

    if /etc/init.d/podkop enabled; then
        /etc/init.d/podkop stop
        /etc/init.d/podkop disable
        led_off
    else
        /etc/init.d/podkop enable
        /etc/init.d/podkop start
        led_on
    fi
}

case "$1" in
    toggle) toggle ;;
    on)
        /etc/init.d/podkop enable
        /etc/init.d/podkop start
        led_on
        ;;
    off)
        /etc/init.d/podkop stop
        /etc/init.d/podkop disable
        led_off
        ;;
    init)
        if /etc/init.d/podkop enabled; then
            led_on
        else
            led_off
        fi
        ;;
    *) echo "Usage: $0 {toggle|on|off|init}" ;;
esac
